.TH "CHAIN" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHAIN \- Information of every chain\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPos\fP [4]"
.br
.RI "\fIxyzr Postion of the chain \fP"
.ti -1c
.RI "double \fBDir\fP [3]"
.br
.RI "\fIDirective of the chain\&. \fP"
.ti -1c
.RI "double \fBVel\fP [3]"
.br
.RI "\fIChain velocity\&. \fP"
.ti -1c
.RI "double \fBAngle\fP"
.br
.ti -1c
.RI "int \fBType\fP"
.br
.RI "\fIType of the chain (see list CHAIN_) \fP"
.ti -1c
.RI "int \fBNPCh\fP"
.br
.RI "\fINumber of particles per chain\&. \fP"
.ti -1c
.RI "int \fBInitBead\fP"
.br
.RI "\fIInitial bead\&. \fP"
.ti -1c
.RI "int \fBEndBead\fP"
.br
.RI "\fIEnd bead\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information of every chain\&. 
.PP
Definition at line 236 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
