.TH "DdFixCell" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdFixCell \- The array of particles in every cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cubo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNPart\fP"
.br
.RI "\fIHow many particles\&. \fP"
.ti -1c
.RI "int * \fBPart\fP"
.br
.RI "\fIId of the particle\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The array of particles in every cell\&. 
.PP
Definition at line 322 of file Cubo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
