.TH "Finestra" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Finestra \- Defines a window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElementiGrafici\&.h>\fP
.PP
Inherits QWidget, and QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFinestra\fP (QWidget *parent=0, const char *name=0)"
.br
.ti -1c
.RI "void \fBDataFile\fP (char **argv, int *FileList, int NFIle)"
.br
.ti -1c
.RI "void \fBConfFile\fP (char *FileName)"
.br
.ti -1c
.RI "\fBFinestra\fP (QWidget *parent=0, const char *name=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a window\&. 
.PP
Definition at line 362 of file ElementiGrafici\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
