.TH "FORCES" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FORCES \- Single contribution of the forces\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Forces\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBDir\fP [3]"
.br
.RI "\fIDirection\&. \fP"
.ti -1c
.RI "double \fBExt\fP [3]"
.br
.RI "\fIExternal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Single contribution of the forces\&. 
.PP
Definition at line 176 of file Forces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
