.TH "GRIDCELL" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GRIDCELL \- All the vertex in a cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBXYZ\fP \fBp\fP [8]"
.br
.RI "\fIVertices\&. \fP"
.ti -1c
.RI "\fBXYZ\fP \fBn\fP [8]"
.br
.RI "\fINormals\&. \fP"
.ti -1c
.RI "double \fBval\fP [8]"
.br
.RI "\fIDensity at the vertices\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
All the vertex in a cell\&. 
.PP
Definition at line 489 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
