.TH "MOMENTI" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MOMENTI \- Moments of a distribution\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBUno\fP"
.br
.RI "\fIFirst moment\&. \fP"
.ti -1c
.RI "double \fBDue\fP"
.br
.RI "\fISecond moment\&. \fP"
.ti -1c
.RI "double \fBTre\fP"
.br
.RI "\fIThird moment\&. \fP"
.ti -1c
.RI "double \fBDelta\fP"
.br
.RI "\fIStep interval\&. \fP"
.ti -1c
.RI "double \fBChi\fP"
.br
.RI "\fIChi square\&. \fP"
.ti -1c
.RI "double \fBMin\fP"
.br
.RI "\fIMinimum value\&. \fP"
.ti -1c
.RI "double \fBMax\fP"
.br
.RI "\fIMaximum value\&. \fP"
.ti -1c
.RI "double \fByMin\fP"
.br
.RI "\fIMinimum of the ordinate\&. \fP"
.ti -1c
.RI "double \fByMax\fP"
.br
.RI "\fIMaximum of the ordinate\&. \fP"
.ti -1c
.RI "int \fBNum\fP"
.br
.RI "\fINumber of points considered\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Moments of a distribution\&. 
.PP
Definition at line 26 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
