.TH "NeiVertex" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeiVertex \- Connects the triangles by vertices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cubo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNeiVertex\fP (int NTriaExt, int NvPtExt, int NGridExt, double *EdgeExt)"
.br
.RI "\fIAlloc NVertices\&. \fP"
.ti -1c
.RI "\fB~NeiVertex\fP ()"
.br
.RI "\fIDelete the class\&. \fP"
.ti -1c
.RI "void \fBAdd\fP (int v, int t, double *Pos)"
.br
.RI "\fIAdd the triangle t at the vertex v\&. \fP"
.ti -1c
.RI "void \fBAdd\fP (double *Pos, int t)"
.br
.RI "\fIAdd the triangle t in the Pos\&. \fP"
.ti -1c
.RI "void \fBRem\fP (int v, int t)"
.br
.RI "\fIRemove the triangle t from the vertex v\&. \fP"
.ti -1c
.RI "void \fBCopyVert2To1\fP (\fBVERTEX\fP Vert1, \fBVERTEX\fP Vert2)"
.br
.RI "\fICopy two vertices\&. \fP"
.ti -1c
.RI "void \fBSwap\fP (int v1, int v2)"
.br
.RI "\fISwap to vertices\&. \fP"
.ti -1c
.RI "void \fBReorder\fP ()"
.br
.RI "\fIReorder and fill the vertices\&. \fP"
.ti -1c
.RI "void \fBSetCounters\fP (int v)"
.br
.RI "\fISet counters to zero for the point v\&. \fP"
.ti -1c
.RI "void \fBSetCounters\fP ()"
.br
.RI "\fISet all the counters to zero\&. \fP"
.ti -1c
.RI "int \fBGetVertex\fP (double *Pos)"
.br
.RI "\fICorrespondent vertes for Pos\&. \fP"
.ti -1c
.RI "int \fBIfItCell\fP (int v)"
.br
.RI "\fIEnd of the counters\&. \fP"
.ti -1c
.RI "void \fBIncrCurr\fP (int v)"
.br
.RI "\fIIncrement the counter\&. \fP"
.ti -1c
.RI "int \fBVertCurr\fP (int v)"
.br
.RI "\fICurrent vertex iterator for the vertex v\&. \fP"
.ti -1c
.RI "int \fBTriaCurr\fP (int v)"
.br
.RI "\fICurrent triangle for the vertex v\&. \fP"
.ti -1c
.RI "void \fBPosVertex\fP (int v, double *Pos)"
.br
.RI "\fIPosition of the vertex v\&. \fP"
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.RI "\fIPrint the entire structure\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Connects the triangles by vertices\&. 
.PP
Definition at line 480 of file Cubo\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void SetCounters (int v)"

.PP
Set counters to zero for the point v\&. Initialize the\&. 
.PP
Definition at line 1093 of file Cubo\&.cpp\&.
.PP
Referenced by VarData::ConnectLineChain2(), and VarData::NormalWeight()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
