.TH "PARABOLA" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PARABOLA \- Parabolas coefficients\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBa0\fP"
.br
.RI "\fIa0 + a1 x + a2 x^2 \fP"
.ti -1c
.RI "double \fBErra0\fP"
.br
.RI "\fIError on the first coefficient\&. \fP"
.ti -1c
.RI "double \fBa1\fP"
.br
.RI "\fIa0 + a1 x + a2 x^2 \fP"
.ti -1c
.RI "double \fBErra1\fP"
.br
.RI "\fIError on the second coefficient\&. \fP"
.ti -1c
.RI "double \fBa2\fP"
.br
.RI "\fIa0 + a1 x + a2 x^2 \fP"
.ti -1c
.RI "double \fBErra2\fP"
.br
.RI "\fIError on the third coefficient\&. \fP"
.ti -1c
.RI "double \fBMinimo\fP"
.br
.RI "\fIMinimum of the parabola\&. \fP"
.ti -1c
.RI "double \fBMinimoY\fP"
.br
.RI "\fIMinimum of the parabola\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Parabolas coefficients\&. 
.PP
Definition at line 7 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
