.TH "Properties" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Properties \- Some calculated properties of the system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperties\fP ()"
.br
.RI "\fISet the values to zero\&. \fP"
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.RI "\fIPrint the current values\&. \fP"
.ti -1c
.RI "\fBProperties\fP \fBoperator+\fP (const \fBProperties\fP &) const "
.br
.ti -1c
.RI "\fBProperties\fP \fBoperator*\fP (const double &) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBRePhob\fP"
.br
.RI "\fIEnd2End distance of the\&. \fP"
.ti -1c
.RI "double \fBRePhil\fP"
.br
.ti -1c
.RI "double \fBVolPhob\fP"
.br
.ti -1c
.RI "double \fBVolPhil\fP"
.br
.ti -1c
.RI "double \fBFactPhob\fP"
.br
.ti -1c
.RI "double \fBFactPhil\fP"
.br
.ti -1c
.RI "double \fBGyrPhob\fP"
.br
.ti -1c
.RI "double \fBGyrPhil\fP"
.br
.ti -1c
.RI "double \fBChDiff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some calculated properties of the system\&. 
.PP
Definition at line 364 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
