.TH "QUADRI" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QUADRI \- Four dimentional vector/quaternion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP [4]"
.br
.RI "\fIw,x,y,z \fP"
.in -1c
.SH "Detailed Description"
.PP 
Four dimentional vector/quaternion\&. 
.PP
Definition at line 81 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
