.TH "Quaternione" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quaternione \- Quaternion operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAxisRotation\fP (double x, double y, double z, double degrees)"
.br
.ti -1c
.RI "void \fBCreateMatrix\fP (double *pMatrix)"
.br
.ti -1c
.RI "\fBQuaternione\fP \fBoperator*\fP (\fBQuaternione\fP q)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Quaternion operations\&. 
.PP
Definition at line 156 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
