.TH "SOFT" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOFT \- Information for every soft object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [60]"
.br
.RI "\fIsoft name \fP"
.ti -1c
.RI "double \fBPos\fP [3]"
.br
.RI "\fIinitial position \fP"
.ti -1c
.RI "double \fBVel\fP [3]"
.br
.RI "\fIbias velocity \fP"
.ti -1c
.RI "double \fBSize\fP [3]"
.br
.RI "\fIdimension xyz/rad height \fP"
.ti -1c
.RI "int \fBTopology\fP"
.br
.RI "\fItopology \fP"
.ti -1c
.RI "int \fBNPart\fP"
.br
.RI "\fI
.SH "particles"
.PP
\fP"
.ti -1c
.RI "int \fBNChain\fP"
.br
.RI "\fI
.SH "chains"
.PP
\fP"
.ti -1c
.RI "int \fBNPCh\fP"
.br
.RI "\fI
.SH "part per chain"
.PP
\fP"
.ti -1c
.RI "int \fBInitIdx\fP"
.br
.RI "\fIInitial Position\&. \fP"
.ti -1c
.RI "int \fBEndIdx\fP"
.br
.RI "\fIEnd position\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information for every soft object\&. 
.PP
Definition at line 276 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
