.TH "Spline" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spline \- coeficients of a N order spline  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpline\fP (int N)"
.br
.RI "\fIAllocate the memory\&. \fP"
.ti -1c
.RI "\fB~Spline\fP ()"
.br
.RI "\fIFree the memory\&. \fP"
.ti -1c
.RI "int \fBGetN\fP ()"
.br
.RI "\fIPrint the number of coefficients\&. \fP"
.ti -1c
.RI "double \fBGetCoe\fP (int n)"
.br
.RI "\fIPrint the n coefficient\&. \fP"
.ti -1c
.RI "void \fBSetCoe\fP (double Val, int n)"
.br
.RI "\fISet the n coefficient\&. \fP"
.ti -1c
.RI "void \fBAddCoe\fP (double Val, int n)"
.br
.RI "\fIAdd to the n coefficient\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
coeficients of a N order spline 
.PP
Definition at line 118 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
