.TH "TENS" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TENS \- Spatial tensor profile\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Forces\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNComp\fP"
.br
.RI "\fI
.SH "of components"
.PP
\fP"
.ti -1c
.RI "int \fBNDim\fP"
.br
.RI "\fI
.SH "of dimensions"
.PP
\fP"
.ti -1c
.RI "int \fBNSlab\fP"
.br
.RI "\fI
.SH "of slabs"
.PP
\fP"
.ti -1c
.RI "int \fBCalcMode\fP"
.br
.RI "\fICalculation mode\&. \fP"
.ti -1c
.RI "double ** \fBPre\fP"
.br
.RI "\fIPressure array\&. \fP"
.ti -1c
.RI "double ** \fBDens\fP"
.br
.RI "\fIDensity array\&. \fP"
.ti -1c
.RI "double \fBPreTot\fP [3]"
.br
.RI "\fITotal pressure\&. \fP"
.ti -1c
.RI "double \fBRefPos\fP [3]"
.br
.RI "\fIReference point\&. \fP"
.ti -1c
.RI "double \fBEdge\fP [3]"
.br
.RI "\fIEdges\&. \fP"
.ti -1c
.RI "int \fBWrap\fP [3]"
.br
.RI "\fIWhich coordinate to wrap\&. \fP"
.ti -1c
.RI "double \fBEdgeInv\fP [3]"
.br
.RI "\fIInverse of the edges\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Spatial tensor profile\&. 
.PP
Definition at line 189 of file Forces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
