.TH "VAR_TRIANGLE" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VAR_TRIANGLE \- Define a triangle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBXYZ\fP \fBp\fP [3]"
.br
.RI "\fIThe three vertices\&. \fP"
.ti -1c
.RI "\fBXYZ\fP \fBc\fP"
.br
.RI "\fICentroid\&. \fP"
.ti -1c
.RI "int \fBv\fP [3]"
.br
.RI "\fIReference for the vectors\&. \fP"
.ti -1c
.RI "\fBXYZ\fP \fBn\fP [3]"
.br
.RI "\fINormal to the vertices\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Define a triangle\&. 
.PP
Definition at line 498 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
