.TH "Variabili" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Variabili \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMatematica\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariabili\fP (int NSegn, int Potenza2, double MediaSu, double ScartoSu, double MediaGiu, double ScartoGiu, double Passo, double Incr)"
.br
.ti -1c
.RI "\fBVariabili\fP (char *NomeMedia, int Valori)"
.br
.ti -1c
.RI "void \fBVerificare\fP (int cosa, int Valore)"
.br
.ti -1c
.RI "bool \fBSimula\fP ()"
.br
.ti -1c
.RI "bool \fBSifula\fP ()"
.br
.ti -1c
.RI "void \fBScriviFile\fP ()"
.br
.ti -1c
.RI "void \fBCambia\fP (char *, int)"
.br
.ti -1c
.RI "void \fBCambia\fP (char *, double)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool * \fBst\fP"
.br
.ti -1c
.RI "double * \fBsMedia\fP"
.br
.ti -1c
.RI "int \fBNMass\fP"
.br
.ti -1c
.RI "int \fBPeriodi\fP"
.br
.ti -1c
.RI "int \fBNSegn\fP"
.br
.ti -1c
.RI "double \fBMediaSu\fP"
.br
.ti -1c
.RI "double \fBScartoSu\fP"
.br
.ti -1c
.RI "double \fBMediaGiu\fP"
.br
.ti -1c
.RI "double \fBScartoGiu\fP"
.br
.ti -1c
.RI "double \fBPasso\fP"
.br
.ti -1c
.RI "double \fBIncr\fP"
.br
.ti -1c
.RI "\fBMatematica\fP * \fBmSu\fP"
.br
.ti -1c
.RI "\fBMatematica\fP * \fBmGiu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file VarSegnali\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
