.TH "VERTEX" 3 "Fri Aug 17 2018" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERTEX \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPos\fP [3]"
.br
.RI "\fIVertex postion\&. \fP"
.ti -1c
.RI "int \fBv\fP"
.br
.RI "\fIVertex id\&. \fP"
.ti -1c
.RI "int \fBt\fP [MAX_JOINT_VERTEX]"
.br
.RI "\fITriangles/lines connected (fixed size!!! should be enough) \fP"
.ti -1c
.RI "int \fBNTria\fP"
.br
.RI "\fINumber of triangles connected to the vertex\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 469 of file Cubo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
