.TH "src/Segnali/ Directory Reference" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Segnali/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSegnali\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSegnali\&.h\fP"
.br
.ti -1c
.RI "file \fBVarSegnali\&.cpp\fP"
.br
.ti -1c
.RI "file \fBVarSegnali\&.h\fP"
.br
.in -1c
