.TH "BLOCK" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLOCK \- 
.PP
Information for every block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [60]"
.br
.RI "\fIBLock name\&. \fP"
.ti -1c
.RI "int \fBNPCh\fP"
.br
.RI "\fI# particles per chain \fP"
.ti -1c
.RI "int \fBNPart\fP"
.br
.RI "\fI# particles \fP"
.ti -1c
.RI "int \fBNChain\fP"
.br
.RI "\fI# chains \fP"
.ti -1c
.RI "int \fBInitIdx\fP"
.br
.RI "\fIInitial particle position\&. \fP"
.ti -1c
.RI "int \fBEndIdx\fP"
.br
.RI "\fIEnd particle position\&. \fP"
.ti -1c
.RI "int \fBArch\fP"
.br
.RI "\fIArchitecture type\&. \fP"
.ti -1c
.RI "int \fBnNano\fP"
.br
.RI "\fINano index\&. \fP"
.ti -1c
.RI "int \fBAsym\fP"
.br
.RI "\fIDiblock limit of the chain\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information for every block\&. 
.PP
Definition at line 255 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
