.TH "CIRCLE" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CIRCLE \- 
.PP
Radius and center of a circle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBRad\fP"
.br
.RI "\fIRadius of the circle\&. \fP"
.ti -1c
.RI "double \fBxC\fP"
.br
.RI "\fIx position of the center \fP"
.ti -1c
.RI "double \fByC\fP"
.br
.RI "\fIy position of the center \fP"
.in -1c
.SH "Detailed Description"
.PP 
Radius and center of a circle\&. 
.PP
Definition at line 49 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
