.TH "Dinamica_page" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dinamica_page \- Dinamica 
Solution of a forth order differential equation on a lattice (solution of the Helfrich Hamiltonian)\&. 
.br
 The boundary condition are represented by the blue and red points, the minimum image convection can be applied or not in every direction\&.
.br
 Optional:OpenGl\&. 
.PD 0

.IP "\(bu" 2
\fBAllink\fP (Up)  
.PP

