.TH "DOMAIN_PART" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DOMAIN_PART \- 
.PP
The previuos and consecutive particle in the cell linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cubo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPos\fP [3]"
.br
.RI "\fIPosition\&. \fP"
.ti -1c
.RI "int \fBNext\fP"
.br
.RI "\fINext particle in the list\&. \fP"
.ti -1c
.RI "int \fBPrev\fP"
.br
.RI "\fIPrevious particle in the list\&. \fP"
.ti -1c
.RI "int \fBCoord\fP"
.br
.RI "\fICoordination number\&. \fP"
.ti -1c
.RI "int \fBCell\fP"
.br
.RI "\fIWhich cell it's belonging\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The previuos and consecutive particle in the cell linked list\&. 
.PP
Definition at line 126 of file Cubo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
