.TH "DomPart" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DomPart \- 
.PP
The previuos and consecutive particle in the cell linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cubo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDomPart\fP (int NPart)"
.br
.ti -1c
.RI "int \fBoperator[]\fP (int col)"
.br
.RI "\fIReturns a entry\&. \fP"
.ti -1c
.RI "\fBDomPart\fP & \fBoperator++\fP ()"
.br
.RI "\fIIncrease the iterator, deactivated\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The previuos and consecutive particle in the cell linked list\&. 
.PP
Definition at line 114 of file Cubo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
