.TH "DrEffect_page" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DrEffect_page \- \fBDrEffect\fP 
The programs perfom analysis on the loaded image and apply different user defined filters (convolution with Gaussian blur or discrete derivative, edge recognition and iterative construction\&.\&.\&.)\&.
.br
 Required:OpenGl Qt4\&.
.PP
.PD 0
.IP "\(bu" 2
\fBAllink\fP (Up)  
.PP

