.TH "DrScript" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DrScript \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBIncrSlide\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecScript\fP (QPainter *p)"
.br
.ti -1c
.RI "void \fBReadSlide\fP (QPainter *p)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file DrScript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
