.TH "ElementiGrafici" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementiGrafici \- 
.PP
Contains the function to interacts with the data stored in \fBVarDatFile\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElementiGrafici\&.h>\fP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBImpNBin\fP (int n)"
.br
.RI "\fISet NBin\&. \fP"
.ti -1c
.RI "void \fBImpNMobile\fP (int n)"
.br
.RI "\fISet the bins for the running average\&. \fP"
.ti -1c
.RI "void \fBImpNCorrela\fP (int n)"
.br
.RI "\fISet the bins for the point correlation\&. \fP"
.ti -1c
.RI "void \fBImpNVisMin\fP (int n)"
.br
.RI "\fISet the minimum visualisation point\&. \fP"
.ti -1c
.RI "void \fBImpNVisMax\fP (int n)"
.br
.RI "\fISet the maximum visualisation point\&. \fP"
.ti -1c
.RI "void \fBImpNElMin\fP (int n)"
.br
.RI "\fISet the minimum elaboration point\&. \fP"
.ti -1c
.RI "void \fBImpNElMax\fP (int n)"
.br
.RI "\fISet the maximum elaboration point\&. \fP"
.ti -1c
.RI "void \fBImpNElMinY\fP (int n)"
.br
.ti -1c
.RI "void \fBImpNElMaxY\fP (int n)"
.br
.ti -1c
.RI "void \fBImpInter\fP (int n)"
.br
.ti -1c
.RI "void \fBImpInterEl\fP (int n)"
.br
.ti -1c
.RI "void \fBImpCoordX\fP (int n)"
.br
.ti -1c
.RI "void \fBImpCoordY\fP (int n)"
.br
.ti -1c
.RI "void \fBImpCoordDY\fP (int n)"
.br
.RI "\fISet the y error bar\&. \fP"
.ti -1c
.RI "void \fBImpNVarX\fP (int n, int m)"
.br
.RI "\fIType for coordinate change\&. \fP"
.ti -1c
.RI "void \fBImpNVarY\fP (int n, int m)"
.br
.ti -1c
.RI "void \fBImpInter\fP (int n, int m)"
.br
.ti -1c
.RI "void \fBImpInterEl\fP (int n, int m)"
.br
.ti -1c
.RI "void \fBImpInterY\fP (int n, int m)"
.br
.ti -1c
.RI "void \fBApri\fP ()"
.br
.ti -1c
.RI "void \fBApri\fP (char **argv, int *FileList, int NFile)"
.br
.ti -1c
.RI "void \fBApriExt\fP (double **ExtSt, int ExtNMax, int ExtNVar, int ExtNBin)"
.br
.ti -1c
.RI "void \fBApriExt\fP (\fBVarDatFile\fP *Extv1)"
.br
.ti -1c
.RI "void \fBAggiungi\fP ()"
.br
.ti -1c
.RI "void \fBPuntiSegnale\fP ()"
.br
.ti -1c
.RI "void \fBPuntiDistribuzione\fP ()"
.br
.ti -1c
.RI "void \fBPuntiSommaSegnali\fP ()"
.br
.ti -1c
.RI "void \fBPuntiInterRett\fP ()"
.br
.ti -1c
.RI "void \fBPuntiInterExp\fP ()"
.br
.ti -1c
.RI "void \fBPuntiInterGauss\fP ()"
.br
.ti -1c
.RI "void \fBPuntiParabola\fP ()"
.br
.ti -1c
.RI "void \fBPuntiMediaMob\fP ()"
.br
.ti -1c
.RI "void \fBPuntiCorrelaADue\fP ()"
.br
.ti -1c
.RI "void \fBPuntiAutosimilarita\fP ()"
.br
.ti -1c
.RI "void \fBPuntiIntegrale\fP ()"
.br
.ti -1c
.RI "void \fBPuntiDerivata\fP ()"
.br
.ti -1c
.RI "void \fBPuntiVarie\fP ()"
.br
.ti -1c
.RI "void \fBPuntiSpettro\fP ()"
.br
.ti -1c
.RI "void \fBPuntiNormalizza\fP ()"
.br
.ti -1c
.RI "void \fBPuntiModulo\fP ()"
.br
.ti -1c
.RI "void \fBPuntiRadice\fP ()"
.br
.ti -1c
.RI "void \fBPuntiAutocor\fP ()"
.br
.ti -1c
.RI "void \fBPuntiSum\fP ()"
.br
.ti -1c
.RI "void \fBDisegnaLinee\fP ()"
.br
.ti -1c
.RI "void \fBDisegnaPunti\fP ()"
.br
.ti -1c
.RI "void \fBDisegnaGriglia\fP ()"
.br
.ti -1c
.RI "void \fBDisegnaLogx\fP ()"
.br
.ti -1c
.RI "void \fBDisegnaLogy\fP ()"
.br
.ti -1c
.RI "void \fBSeRiscala\fP ()"
.br
.ti -1c
.RI "void \fBSeRiscalaTutto\fP ()"
.br
.ti -1c
.RI "void \fBNSet\fP ()"
.br
.ti -1c
.RI "void \fBStampaFile\fP ()"
.br
.ti -1c
.RI "void \fBPuntaExt\fP (double **ExtSt, int nVar)"
.br
.ti -1c
.RI "void \fBSulSegnale\fP (bool)"
.br
.ti -1c
.RI "void \fBSulGrafico\fP (bool)"
.br
.ti -1c
.RI "void \fBSuX\fP (bool)"
.br
.ti -1c
.RI "void \fBSuY\fP (bool)"
.br
.ti -1c
.RI "void \fBSuDX\fP (bool)"
.br
.ti -1c
.RI "void \fBSuDY\fP (bool)"
.br
.ti -1c
.RI "void \fBRidisegna\fP ()"
.br
.ti -1c
.RI "void \fBInfoStato\fP (const char *)"
.br
.ti -1c
.RI "void \fBInfoSequenza\fP (const char *)"
.br
.ti -1c
.RI "void \fBSalva\fP ()"
.br
.ti -1c
.RI "void \fBNomeFile\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeConf\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeEntrata\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeSalva\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeUscita\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeTitolo\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeEtichettaX\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeEtichettaY\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeTit\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeEtX\fP (const QString &)"
.br
.ti -1c
.RI "void \fBNomeEtY\fP (const QString &)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBNBinCambiati\fP (int)"
.br
.ti -1c
.RI "void \fBNMobileCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNCorrelaCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNVisMinCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNVisMaxCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNElMinCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNElMaxCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNElMinYCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBNElMaxYCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBLogxCambiato\fP (bool)"
.br
.ti -1c
.RI "void \fBLogyCambiato\fP (bool)"
.br
.ti -1c
.RI "void \fBMediaCambiata\fP (int)"
.br
.ti -1c
.RI "void \fBScartoCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBInterVisCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBInterElCambiato\fP (int)"
.br
.ti -1c
.RI "void \fBInterVisCambiato\fP (int, int)"
.br
.ti -1c
.RI "void \fBInterElCambiato\fP (int, int)"
.br
.ti -1c
.RI "void \fBInterYCambiato\fP (int, int)"
.br
.ti -1c
.RI "void \fBCoordXCambiata\fP (int)"
.br
.ti -1c
.RI "void \fBCoordYCambiata\fP (int)"
.br
.ti -1c
.RI "void \fBInterCoordXCambiato\fP (int, int)"
.br
.ti -1c
.RI "void \fBInterCoordYCambiato\fP (int, int)"
.br
.ti -1c
.RI "void \fBFineSimulazione\fP ()"
.br
.ti -1c
.RI "void \fBSegnaleGrafico\fP (bool)"
.br
.ti -1c
.RI "void \fBStato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBStatoSequenza\fP (const QString &)"
.br
.ti -1c
.RI "void \fBTestoCambiato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBConfCambiato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBSalvaCambiato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBTitoloCambiato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBEtichettaXCambiato\fP (const QString &)"
.br
.ti -1c
.RI "void \fBEtichettaYCambiato\fP (const QString &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementiGrafici\fP (QWidget *parent=0, const char *name=0)"
.br
.RI "\fIGeneral constructor\&. \fP"
.ti -1c
.RI "\fB~ElementiGrafici\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "QSizePolicy \fBDimensionamento\fP () const "
.br
.ti -1c
.RI "void \fBChooseDataFile\fP (char *FileName)"
.br
.RI "\fIChoose the input file\&. \fP"
.ti -1c
.RI "void \fBChooseConfFile\fP (char *FileName)"
.br
.RI "\fIChoose the configuration file\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNMax\fP"
.br
.RI "\fINumber of points per array\&. \fP"
.ti -1c
.RI "int \fBNDis\fP"
.br
.RI "\fICurrent number of visualisation (debugging) \fP"
.ti -1c
.RI "\fBVarDatFile\fP * \fBv1\fP"
.br
.RI "\fIClass for the file handle\&. \fP"
.ti -1c
.RI "char * \fBnomeFile\fP"
.br
.RI "\fIName of the current file opened\&. \fP"
.ti -1c
.RI "char * \fBnomeConf\fP"
.br
.RI "\fIName of the config file\&. \fP"
.ti -1c
.RI "char * \fBnomeSalva\fP"
.br
.RI "\fIName of the output file\&. \fP"
.ti -1c
.RI "QString \fBnomeTit\fP"
.br
.RI "\fITitle name\&. \fP"
.ti -1c
.RI "QString \fBnomeEtX\fP"
.br
.RI "\fIX axis label\&. \fP"
.ti -1c
.RI "QString \fBnomeEtY\fP"
.br
.RI "\fIY axis label\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *)"
.br
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QMouseEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the function to interacts with the data stored in \fBVarDatFile\fP\&. 
.PP
Definition at line 83 of file ElementiGrafici\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBImpNVarX\fP (intn, intm)\fC [slot]\fP"
.PP
Type for coordinate change\&. Pointer to a coordinate change function 
.PP
Definition at line 362 of file ElementiGraficiComm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
