.TH "KFORCES" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KFORCES \- 
.PP
Prefactors of the forces\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Forces\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBLap\fP"
.br
.RI "\fIPrefactor of the Laplacian\&. \fP"
.ti -1c
.RI "double \fBSLap\fP"
.br
.RI "\fIPrefactor of the square laplacian\&. \fP"
.ti -1c
.RI "double \fBEl\fP [3]"
.br
.RI "\fIElastic force\&. \fP"
.ti -1c
.RI "double \fBExt\fP"
.br
.RI "\fIExternal force\&. \fP"
.ti -1c
.RI "double \fBLJ\fP"
.br
.RI "\fILennard-Jones\&. \fP"
.ti -1c
.RI "double \fBCont\fP"
.br
.RI "\fIContact/Friction\&. \fP"
.ti -1c
.RI "double \fBElong\fP [3]"
.br
.RI "\fIElongation of the springs\&. \fP"
.ti -1c
.RI "double \fBLJMin\fP"
.br
.RI "\fILennard-Jones\&. \fP"
.ti -1c
.RI "double \fBLJCutOff\fP"
.br
.RI "\fILennard-Jones\&. \fP"
.ti -1c
.RI "double \fBCutOff2\fP"
.br
.RI "\fICutOff of the lennard jones\&. \fP"
.ti -1c
.RI "double \fBBaseLine\fP"
.br
.RI "\fIBaseline of the potential\&. \fP"
.ti -1c
.RI "double \fBPotThr\fP"
.br
.RI "\fIMaximum potential allowed\&. \fP"
.ti -1c
.RI "double \fBForThr\fP"
.br
.RI "\fIMaximum force allowed\&. \fP"
.ti -1c
.RI "double \fBDistThr\fP"
.br
.RI "\fICorrespondent radial distance for this force\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Prefactors of the forces\&. 
.PP
Definition at line 145 of file Forces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
