.TH "NANO" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NANO \- 
.PP
Information about the nanoparticle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBArchFile\fP [60]"
.br
.RI "\fIArchitecture file\&. \fP"
.ti -1c
.RI "double \fBPos\fP [3]"
.br
.RI "\fIPosition\&. \fP"
.ti -1c
.RI "double \fBBkf\fP [3]"
.br
.RI "\fIBackfolded position\&. \fP"
.ti -1c
.RI "double \fBVel\fP [3]"
.br
.RI "\fIVelocity\&. \fP"
.ti -1c
.RI "double \fBForce\fP [3]"
.br
.RI "\fI\fBForces\fP\&. \fP"
.ti -1c
.RI "double \fBAxis\fP [3]"
.br
.RI "\fIRotation axis\&. \fP"
.ti -1c
.RI "double \fBAMom\fP [3]"
.br
.RI "\fIAngular momentum\&. \fP"
.ti -1c
.RI "double \fBAMomTemp\fP [3]"
.br
.RI "\fITemporal angular momentum\&. \fP"
.ti -1c
.RI "double \fBAVel\fP [3]"
.br
.RI "\fIAngular velocity\&. \fP"
.ti -1c
.RI "double \fBMass\fP"
.br
.RI "\fIMass\&. \fP"
.ti -1c
.RI "double \fBRad\fP"
.br
.RI "\fISize\&. \fP"
.ti -1c
.RI "double \fBHamaker\fP"
.br
.RI "\fIStrength of the interaction\&. \fP"
.ti -1c
.RI "double \fBHeight\fP"
.br
.RI "\fIHeight of the cylinder\&. \fP"
.ti -1c
.RI "double \fBGamma\fP"
.br
.RI "\fIFriction term\&. \fP"
.ti -1c
.RI "double \fBZeta\fP"
.br
.RI "\fIStochastic term\&. \fP"
.ti -1c
.RI "double \fBViscosity\fP"
.br
.RI "\fIViscosity\&. \fP"
.ti -1c
.RI "double \fBOffSet\fP"
.br
.RI "\fIReference potential\&. \fP"
.ti -1c
.RI "double \fBCutOff\fP"
.br
.RI "\fICut off of the potential\&. \fP"
.ti -1c
.RI "double \fBCoating\fP"
.br
.RI "\fIThickness of the LJ well\&. \fP"
.ti -1c
.RI "double \fBBaseLine\fP"
.br
.RI "\fIBaseline of the potential\&. \fP"
.ti -1c
.RI "double \fBDistThr\fP"
.br
.RI "\fIMinimum distance threshold\&. \fP"
.ti -1c
.RI "double \fBForThr\fP"
.br
.RI "\fIMaximum value of the force\&. \fP"
.ti -1c
.RI "double \fBPotThr\fP"
.br
.RI "\fIMaximum value of the potential\&. \fP"
.ti -1c
.RI "double \fBArea\fP"
.br
.RI "\fIArea of a pore or a stalk\&. \fP"
.ti -1c
.RI "int \fBShape\fP"
.br
.RI "\fI0 none, 1 spherical, 2 cylindrical 3 wall \fP"
.ti -1c
.RI "int \fBNLink\fP"
.br
.RI "\fINumber of links connecting the constituent monomers\&. \fP"
.ti -1c
.RI "int \fBNHeight\fP"
.br
.RI "\fINumber of monomers per side\&. \fP"
.ti -1c
.RI "int \fBNCircle\fP"
.br
.RI "\fINumber of monomers per circle\&. \fP"
.ti -1c
.RI "int \fBnBlock\fP"
.br
.RI "\fIIn which block is the peptide written\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information about the nanoparticle\&. 
.PP
Definition at line 423 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
