.TH "PART" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PART \- 
.PP
Information of every particle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VarData\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPos\fP [3]"
.br
.RI "\fIxyz Position of the particle \fP"
.ti -1c
.RI "double \fBBkf\fP [3]"
.br
.RI "\fIxyz Backfold distance \fP"
.ti -1c
.RI "double \fBVel\fP [4]"
.br
.RI "\fIxyzr Velocity of the particle \fP"
.ti -1c
.RI "int \fBIdx\fP"
.br
.RI "\fIParticle identifier\&. \fP"
.ti -1c
.RI "int \fBCId\fP"
.br
.RI "\fIChain Identifier\&. \fP"
.ti -1c
.RI "int \fBTyp\fP"
.br
.RI "\fIType\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information of every particle\&. 
.PP
Definition at line 214 of file VarData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
