.TH "PERMUTE" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PERMUTE \- 
.PP
Indices for the permutation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.RI "\fIFirst number of the couple\&. \fP"
.ti -1c
.RI "int \fBm\fP"
.br
.RI "\fISecond number of the couple\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Indices for the permutation\&. 
.PP
Definition at line 97 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
