.TH "RADICE" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RADICE \- 
.PP
Where a root was searched\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBiLim\fP"
.br
.RI "\fIIferior limit\&. \fP"
.ti -1c
.RI "double \fBsLim\fP"
.br
.RI "\fISuperior limit\&. \fP"
.ti -1c
.RI "double \fBZero\fP"
.br
.RI "\fIPoint of the zero\&. \fP"
.ti -1c
.RI "int \fBIfRis\fP"
.br
.RI "\fIIf the zero was founds\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Where a root was searched\&. 
.PP
Definition at line 86 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
