.TH "RETTA" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RETTA \- 
.PP
Linear interpolation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBm\fP"
.br
.RI "\fIy = m*x + q \fP"
.ti -1c
.RI "double \fBErrM\fP"
.br
.RI "\fIError on the slope\&. \fP"
.ti -1c
.RI "double \fBq\fP"
.br
.RI "\fIy = m*x + q \fP"
.ti -1c
.RI "double \fBErrQ\fP"
.br
.RI "\fIError on the intercept\&. \fP"
.ti -1c
.RI "double \fBCorr\fP"
.br
.RI "\fICorrelation\&. \fP"
.ti -1c
.RI "double \fBCov\fP"
.br
.RI "\fICovariance\&. \fP"
.ti -1c
.RI "double \fBr\fP"
.br
.RI "\fIr factor \fP"
.ti -1c
.RI "double \fBErrY\fP"
.br
.RI "\fIError a posteriori\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linear interpolation\&. 
.PP
Definition at line 57 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
