.TH "SingProc" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingProc \- 
.PP
Basics class to start a MPI grid\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SingProc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingProc\fP (int ExtSize, int ExtRank)"
.br
.ti -1c
.RI "\fBSingProc\fP (int ExtSize, int ExtRank, int ExtNRow, int ExtNCol)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBRank\fP"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.ti -1c
.RI "MPI_Comm \fBCommGrid\fP"
.br
.ti -1c
.RI "MPI_Comm \fBCommRow\fP"
.br
.ti -1c
.RI "MPI_Comm \fBCommCol\fP"
.br
.ti -1c
.RI "int \fBCol\fP"
.br
.ti -1c
.RI "int \fBRow\fP"
.br
.ti -1c
.RI "int \fBNDim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basics class to start a MPI grid\&. 
.PP
Definition at line 6 of file SingProc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
