.TH "SpecFuntore< Classe >" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecFuntore< Classe > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFuntore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecFuntore\fP (Classe *_pt2Object, void(Classe::*_ftp)(double x))"
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (const double x)"
.br
.ti -1c
.RI "virtual double \fBCall\fP (double x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Classe>class SpecFuntore< Classe >"

.PP
Definition at line 345 of file Matematica\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
