.TH "VETT" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VETT \- 
.PP
Three dimentional vector\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatematicaStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP [3]"
.br
.RI "\fIPosition\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Three dimentional vector\&. 
.PP
Definition at line 76 of file MatematicaStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Allink from the source code\&.
