.TH "Visualizza_page" 3 "Thu Mar 27 2014" "Version v0.1" "Allink" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Visualizza_page \- Visualizza 
Program for signal analysis:
.br
 The programs loads a list of files assuming the first coordinate as x; the x and y coordinate can be changed with the right-up slider\&. 
.br
 The lower left box choose the options for the visualisation (single set, log log, riscale\&.\&.\&.)\&. 
.br
 The lower sliders select the points for visualisation and analysis\&. The bottons on the rhs perform fittings, running average, distributions, integration\&.\&.\&. 
.br
 Required:Qt4\&. 
.PD 0

.IP "\(bu" 2
\fBAllink\fP (Up)  
.PP

