Allink: Matrice Class Reference
Matrice Class Reference
Matrice computes the algebric operations on matrices.
#include <MatematicaMatrix.h>
Public Member Functions
Matrice (int newNSize)
creates a square Matrice
Matrice (int NRow, int NCol)
Creates a NRow x NCol Matrice.
Matrice (int NRow, int NCol, int NZed)
Creates a NRow x NCol x NZed Matrice.
Matrice (int ExtNRow, int ExtNCol, double *pointer)
Creates a NRow x NCol Matrice which points to an already allocated double.
Matrice (SPLINE Wg)
A 3x3 Matrice defined as discreate two dimensional derivation operator.
Matrice (SPLINE Wg, int Dim)
A 5x5 Matrice defined as discrete two dimensional derivation operator, Dim defines different options.
Matrice (Quadri q, int dim)
a 4x4 or 3x3 Matrice defined by a quaternion
Matrice (double *M, int Nr, int Nc)
The data array point to an alreay allocated array.
Matrice (double Roll, double Pitch, double Yaw, int NDim)
Define a rotation matrix from Euler angles.
Matrice (double *Axis, double Angle, int NDim)
Define a rotation matrix from a axis and a rotation angle.
~Matrice ()
Freeing.
bool Set (int row, int column, double Val)
Set a coefficient.
bool Add (int row, int col, double Val)
Add the value of the coefficient to the previous one.
int Size ()
Size of Matrice.
int pNCol ()
Number of columns.
int pNRow ()
Number of rows.
int pNZed ()
Number of zed.
void Apply (double *Known, double *UnKnown)
Apply Ax = y.
int Solve (double *Known, double *UnKnown)
Solve a system A|b = y.
int getNRow ()
Return size.
void Shout (const char *s,...)
Name of the last function called. For debugging.
void comparetoidentity ()
Compare to identity.
void settoproduct (Matrice &left, Matrice &right)
Set to product.
void copymatrix (Matrice &source)
Copy matrix.
void setNRow (int newNRow)
Set new size.
void getvalue (int row, int column, double &returnvalue, bool &success)
Return value.
void Invert ()
Invert.
void Mult (Matrice &A, Matrice &B)
Multiplication between two matrices.
void Mult (Matrice &A)
Multiplication by matrices.
Vettore Mult (Matrice &A, Vettore &v)
Multiplication by a vector.
Vettore Mult (Vettore &v)
Multiplication by a vector.
void Mult (Vettore &v, Vettore &u)
Multiplication by a vector on a vector u.
void RandomFill (double Max)
Fill the entries randomly.
void FillDiffOperator (SPLINE Wg, int NDim)
Fill the entries of a differential operator.
void FillCanny ()
Fill the entries for the Canny edge detector.
void FillGaussian (double Sigma, double CutOff)
Fill the entries for the Gauss blur.
void FillGaussian5 ()
Fill the entries for the 5x5 Gauss blur.
void Transpose ()
Transpose the matrix.
void Normalize ()
Normalize the matrix.
void Clear ()
Set all the entries to zero.
void Multiply (double Val)
Multiply by a scalar.
void CopyOn (Matrice *B)
Copy on a matrix.
void Print ()
Print the entries.
double Val (int row)
Returns a value in 1d.
double Val (int row, int col)
Returns a value in 2d.
double Val (int row, int col, int zed)
Returns a value in 3d.
double Det ()
Computes the determinants.
Matrice operator+ (Matrice &)
Sums two matrices.
Matrice operator* (Matrice &A)
Multiplies two matrices.
Matrice operator* (const double &) const
Multiplies per a scalar.
Vettore operator* (const Vettore &) const
Multiplies per a vector.
Matrice operator= (Matrice &)
Copy two matrices.
Matrice operator^ (Matrice &) const
Tensor product?
void ConvoluteMatrix (double *Plot, int NGrid, int NDim, int IfMinImConv)
Convolute with a matrix.
void ConvoluteMatrix1 (double *Plot, int NGrid)
Convolute with a matrix.
void ConvoluteMatrix1MinImConv (double *Plot, int NGrid)
Convolute with a matrix.
void ConvoluteMatrix2 (double *Plot, int NGrid)
Convolute with a matrix.
void ConvoluteMatrix2MinImConv (double *Plot, int NGrid)
Convolute with a matrix.
void ConvoluteMatrix3 (double *Plot, int NGrid)
Convolute with a matrix.
Public Attributes
double * data
Stored entries.
Detailed Description
Matrice computes the algebric operations on matrices.
Definition at line 10 of file MatematicaMatrix.h.
Constructor & Destructor Documentation
Matrice (Quadri q, int dim)
a 4x4 or 3x3 Matrice defined by a quaternion
Parameters:
Quadri q
Definition at line 154 of file MatematicaAlgebra.cpp.
References data, Quadri::w, Quadri::x, Quadri::y, and Quadri::z.
Member Function Documentation
void ConvoluteMatrix2 (double * Plot, int NGrid)
Convolute with a matrix.
no minimum image convention
Definition at line 999 of file MatematicaAlgebra.cpp.
References pNCol(), pNRow(), and Val().
Referenced by ConvoluteMatrix().
void ConvoluteMatrix2MinImConv (double * Plot, int NGrid)
Convolute with a matrix.
with minimum image convention
Definition at line 1037 of file MatematicaAlgebra.cpp.
References pNCol(), pNRow(), and Val().
Referenced by ConvoluteMatrix().
The documentation for this class was generated from the following files:
include/MatematicaMatrix.h
src/Matematica/MatematicaAlgebra.cpp